api_token: ""
chat_id: null
login_manger: false
log_status: true
enable_chat: true
enable_dithering: false
language: ru
registration_messages:
  eng:
    already_bound: "&cIt seems like your account is already bound to Telegram."
    register_prefix: "&eTo finish registration, open "
    register_link: "&c&nthis link"
    register_suffix: "&e or PM @%s this code: &c%s&e. &7Do not share it with anyone."
    signup_success: "&aYou are signed up now."
    signup_failed: "&cSomething went wrong."
    link_hover: "&7Telegram - %s"
  ru:
    already_bound: "&cПохоже, ваш аккаунт уже привязан к Telegram."
    register_prefix: "&eЧтобы завершить регистрацию, откройте "
    register_link: "&c&nэту ссылку"
    register_suffix: "&e или отправьте боту @%s в ЛС код: &c%s&e. &7Никому его не передавайте."
    signup_success: "&aВы успешно зарегистрированы."
    signup_failed: "&cЧто-то пошло не так."
    link_hover: "&7Telegram - %s"
  ua:
    already_bound: "&cЗдається, ваш акаунт вже прив'язаний до Telegram."
    register_prefix: "&eЩоб завершити реєстрацію, відкрийте "
    register_link: "&c&nце посилання"
    register_suffix: "&e або надішліть боту @%s в приватні повідомлення код: &c%s&e. &7Нікому його не передавайте."
    signup_success: "&aВи успішно зареєструвалися."
    signup_failed: "&cЩось пішло не так."
    link_hover: "&7Telegram - %s"
ngrok_auth: ""
