name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
api-version: 1.13

main: ${mainClass}
commands:
  log:
    description: No description
    permission: ${name}.test
    usage: /<command> 
    default: true


permissions:
    ${name}.*:
      description: permission
      default: true
