name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Retrieve saved jar
      uses: actions/download-artifact@v2
      with:
        name: 'tg-bridge.jar'
        #path: path/to/artifacts
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "tg-bridge.jar"
        token: ${{ secrets.GITHUB_TOKEN }}
